### PR TITLE
Now blocks can be entities too

### PR DESCRIPTION
**Pull request by snakefangox**
I'm sure they felt left out.

### CODE REVIEW

**Comment by ErdbeerbaerLP** [comment]
What about fluids?

**Comment by snakefangox** [comment]
Fluids too

**Comment by snakefangox** [comment]
Fluids are just floppy blocks anyway.

**Comment by ErdbeerbaerLP** [comment]
Neat _(is a mod by vazkii)_

**Comment by snakefangox** [comment]
Fixed merge conflicts

**Comment by JamiesWhiteShirt** [comment]
Please explicitly state when you re-use code from another mod next time.

**Pull request merged**
