### PR TITLE
add SexyFont client submod

### PR DESCRIPTION
**Pull request by quat1024**
This makes the minecraft text renderer a whole lot gooder

sample: https://i.imgur.com/Yeckp4U.gifv

### CODE REVIEW

**Comment by Cadiboo** [comment]
This is required

**Comment by quat1024** [comment]
i agree

**Comment by kierajreed** [comment]
ooh, that's hot

**Comment by Cadiboo** [comment]
Why isn’t this accepted yet

**Comment by itsmeow** [comment]
pls accept

**Comment by quat1024** [comment]
hi discord

**Comment by kierajreed** [comment]
#StartTheRevolution

**Comment by Darkhax** [comment]
Dab

**Comment by kierajreed** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Cadiboo** [comment]
damn

**Pull request merged**
